version: "2.4"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - 8181:8080
      - 8787:8787
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
#      - "KEYCLOAK_LOGLEVEL=DEBUG"
      - "DEBUG_PORT=*:8787"
      - "DEBUG=true"
#      - "KEYCLOAK_IMPORT=/opt/jboss/keycloak/standalone/deployments/realm-export.json"
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile=preview"]
    volumes:
      - ./keycloak:/opt/jboss/keycloak/standalone/deployments
      - ./src/main/keycloak/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
#      - ./theme/noderunners:/opt/jboss/keycloak/themes/noderunners
